# Generated by Django 5.0.6 on 2024-05-20 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_alter_task_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.user'),
        ),
    ]
