# Generated by Django 5.0.6 on 2024-05-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_task_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='owner_id',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
