# Generated by Django 5.0.6 on 2024-05-20 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_alter_task_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='task',
            name='taskid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
